/**
 * Central place for every Hugeicons glyph used across the WhatsApp UI, aliased
 * to friendly names so components read clearly.
 */
export {
  // Navigation & chrome
  Search01Icon as SearchIcon,
  Cancel01Icon as CloseIcon,
  MessageAdd01Icon as NewChatIcon,
  MoreVerticalIcon as MoreIcon,
  BubbleChatIcon as ChatsIcon,
  UserGroupIcon as CommunitiesIcon,
  Settings01Icon as SettingsIcon,
  Archive01Icon as ArchiveIcon,
  FilterIcon as FilterIcon,
  Moon02Icon as MoonIcon,
  Sun03Icon as SunIcon,
  ArrowLeft01Icon as BackIcon,
  ArrowDown01Icon as ChevronDownIcon,
  QrCodeIcon as QrCodeIcon,
  Logout01Icon as LogoutIcon,
  // Calls
  Call02Icon as PhoneIcon,
  Video01Icon as VideoIcon,
  CallIncoming01Icon as CallIncomingIcon,
  CallOutgoing01Icon as CallOutgoingIcon,
  CallMissed01Icon as CallMissedIcon,
  CallEnd01Icon as CallEndIcon,
  MicOff01Icon as MicOffIcon,
  VideoOffIcon as VideoOffIcon,
  VolumeHighIcon as SpeakerIcon,
  // Composer
  Attachment01Icon as AttachIcon,
  PlusSignIcon as PlusIcon,
  SmileIcon as EmojiIcon,
  Mic01Icon as MicIcon,
  SentIcon as SendIcon,
  PlayIcon as PlayIcon,
  PauseIcon as PauseIcon,
  Delete02Icon as DeleteIcon,
  // Receipts
  Tick01Icon as CheckIcon,
  TickDouble01Icon as CheckDoubleIcon,
  Clock01Icon as ClockIcon,
  // Message actions
  ArrowTurnBackwardIcon as ReplyIcon,
  Share08Icon as ForwardIcon,
  StarIcon as StarIcon,
  PinIcon as PinIcon,
  Copy01Icon as CopyIcon,
  PencilEdit01Icon as EditIcon,
  CheckmarkCircle01Icon as SelectIcon,
  // Media
  Camera01Icon as CameraIcon,
  Image01Icon as ImageIcon,
  File01Icon as DocumentIcon,
  Download01Icon as DownloadIcon,
  Location01Icon as LocationIcon,
  UserCircleIcon as ContactIcon,
  // Info panel & settings
  VolumeOffIcon as MuteIcon,
  Notification01Icon as NotificationIcon,
  SquareLock01Icon as LockIcon,
  BlockedIcon as BlockIcon,
  AlertCircleIcon as ReportIcon,
  UserMultipleIcon as MembersIcon,
  // CRM, automations & AI
  KanbanIcon as PipelineIcon,
  Tag01Icon as TagIcon,
  Building01Icon as CompanyIcon,
  Mail01Icon as MailIcon,
  UserAccountIcon as OwnerIcon,
  DollarCircleIcon as ValueIcon,
  Note01Icon as NoteIcon,
  Analytics01Icon as TimelineIcon,
  WorkflowSquare01Icon as AutomationIcon,
  FlashIcon as RunIcon,
  AiBrain01Icon as AiIcon,
  SparklesIcon as SparklesIcon,
  MagicWand01Icon as SuggestIcon,
  Target01Icon as SentimentIcon,
  // Advisory workspaces
  Wallet01Icon as WalletIcon,
  Calendar03Icon as AgendaIcon,
  UserSearch01Icon as ClientsIcon,
  Megaphone01Icon as CampaignIcon,
  Target02Icon as GoalIcon,
  PieChartIcon as AllocationIcon,
  ChartLineData01Icon as PerformanceIcon,
  CakeIcon as BirthdayIcon,
  ShieldKeyIcon as SuitabilityIcon,
  Award01Icon as NpsIcon,
  Briefcase01Icon as ProfessionIcon,
  Money03Icon as ContributionIcon,
  Note02Icon as MeetingIcon,
  FilterHorizontalIcon as FilterIcon2,
  Rocket01Icon as PublishIcon,
  Copy01Icon as DuplicateIcon,
  CheckmarkCircle01Icon as ApproveIcon,
} from "@hugeicons/core-free-icons"
